SecretNumberGame/Controllers/ScoreBoardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SecretNumberGame.Data;
using SecretNumberGame.Data.Constants;
using SecretNumberGame.Services.Contracts;
using SecretNumberGame.Services.Models;
using System.Security.Claims;

namespace SecretNumberGame.Controllers
{
    public class ScoreBoardController : BaseController
    {
        
        private readonly IScoreBoardService service;

        public ScoreBoardController(IScoreBoardService _service)
        {            
            service = _service;
        }
        
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> GetAllUsersScore()
        {
            var modelNumber = await service.GetScore();

            return View(modelNumber);
        }

        [HttpPost]
        [Authorize(Policy = GlobalConstants.MY_POLICY)]
        public async Task<IActionResult> ResetScoreBoard()
        {
            await service.ClearScore();

            return RedirectToAction(nameof(GetAllUsersScore));
        }

        [HttpGet]        
        public async Task<IActionResult> MyScore() 
        {
            var userId = User?.Claims?.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)?.Value;
            if (userId != null)
            {
               var myScore = await service.GetMyScore(userId);
                return View(myScore);
            }
            return RedirectToAction("Index","Home");
        }
    }
}

SecretNumberGame/Views/ScoreBoard/GetAllUsersScore.cshtml
@using SecretNumberGame.Data.Constants
@model IEnumerable<ScoreViewModel>
@{
    ViewBag.Title = "Scoreboard";
    var maxGold = -1;
}
<h2 class="text-center">@ViewBag.Title</h2>
<hr class="container w-25 align-content-center"/>
<hr class="container w-50 align-content-center"/>
<hr class="container w-75 align-content-center"/>

@if (User?.Identity?.IsAuthenticated?? false)
{
    <div class="container card-body bg-info bg-opacity-25 rounded-pill shadow-lg w-100 align-content-center">
        <table class="table-bordered table table-hover table-responsive border-secondary box-shadow shadow-lg container w-75">

            <thead class="bg-info">
                <tr class="align-content-center">
                    <th style="width:15%">
                        <h6>❍ Names 🕴️❍</h6>
                    </th>
                    <th style="width:11%">
                        <h6>❍ Games ❍</h6>
                    </th>
                    <th style="width:22%">
                        <h6>❍ Gold Earned 🏅❍</h6>
                    </th>
                    <th style="width:22%">
                        <h6>❍ Average Gold/Game ❍</h6>
                    </th>
                    <th style="width:18%">
                        <h6>❍ Best Time ⏱❍</h6>
                    </th>
                    <th style="width:16%">
                        <h6>❍ Winner ❍</h6>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var user in Model)
                {
                    <tr class="bg-danger bg-opacity-10">
                        <td>
                            <h6>@user.UserNames</h6>
                        </td>
                        <td>
                            <h6>@user.UserTotalGames</h6>
                        </td>
                        <td>
                            <div class="container list-group list-group-horizontal">
                                <h6 class="m-3">@user.TotalGold 💰</h6>
                                <select class="form-control-sm dropdown-divider" style="background-color:lightgreen;touch-action:cross-slide-x;font-weight:400">
                                    <option>All </option>
                                    @for (int i = 0; i < user.GoldAllGames.Count; i++)
                                    {
                                        <option style="font-weight:400">

                                            @($"{user.GoldAllGames[i].Value} gold")

                                        </option>

                                    }

                                </select>
                            </div>
                        </td>

                        <td>
                            <h6>@(user.AverageGoldEarned.ToString("f2")) gold / game</h6>
                        </td>
                        <td>
                            @if (double.Parse(user.BestDuration) < 60)
                            {
                                <h6>0 min @user.BestDuration sec</h6>
                            }
                            else
                            {
                                if ((double.Parse(user.BestDuration) - 60) < 60)
                                {
                                    <h6> 1 min @((double.Parse(user.BestDuration) - 60).ToString("f2")) sec</h6>
                                }
                                else
                                {
                                    <h6> @(Math.Floor(double.Parse(user.BestDuration) / 60)) min @(((double.Parse(user.BestDuration) / 60 - (Math.Floor(double.Parse(user.BestDuration) / 60))) * 60).ToString("f2")) sec</h6>
                                }

                            }

                        </td>
                        <td>
                            @if (user.HasBestTime && user.HasBestTotalScore)
                            {
                                <h6>🏆</h6>
                            }
                            else
                            {
                                <h6>㋛</h6>
                            }

                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
}
else
{
    <div class="bg-warning bg-opacity-25 text-center text-danger rounded-pill">
        <h5> You have to be logged-in to your account for full info.</h5>
    </div>
}
<hr class="container w-75 align-content-center" />
<hr class="container w-50 align-content-center" />
<hr class="container w-25 align-content-center" />

@if (User.IsInRole(GlobalConstants.PLAYER))
{
    <form method="post">
        <div class="text-center m-3">
            <input type="submit" asp-action="ResetScoreBoard" asp-controller="ScoreBoard" value="Reset Score" class="btn btn-warning btn-outline-danger align-content-center w-auto rounded-pill box-shadow shadow-lg" />
        </div>
    </form>
}

SecretNumberGame/Views/ScoreBoard/MyScore.cshtml
@model IEnumerable<MyScoreViewModel>
@{
	string names = "";
	string email = "";
	if (Model.Count() != 0)
	{
		names = Model.Select(x => x.UserNames).First();
		email = Model.Select(x => x.Email).First();
		ViewBag.Title = $"Personal Game Score - {names} ✉{email}";
	}
	else
	{
		ViewBag.Title = $"Personal Game Score";
	}
	
	
	var count = 1;
}
<div class="container bg-info bg-opacity-25 rounded-pill align-content-center shadow box-shadow shadow-lg">
	<div class="container text-center align-content-center w-100">
		<div style="color:dodgerblue"sty class=" container bg-success bg-opacity-25  rounded-pill w-75 shadow box-shadow shadow-lg">
			<h4>@ViewBag.Title</h4>
		</div>
	</div>
	<hr class="container w-75" />
	@if (Model.Count() == 0)
	{
		<hr />
		<div class="container text-danger text-center bg-info bg-opacity-25 rounded-pill">
			<h4>There are currently no game records saved.</h4>
			<h4>Consider starting a new Game to get some fresh score results here!</h4>
		</div>
	}
	<div class="container align-content-center rounded-pill bg-info bg-opacity-10 w-100 shadow shadow-lg box-shadow">
		@foreach (var score in Model)
		{

			<table class="container w-75 table table-bordered table-hover table-responsive-lg border-secondary">
				<thead>
					<tr class="bg-info bg-opacity-75">
						<th width="10%">
							Game No:
						</th>
						<th width="12%">
							Start Time
						</th>
						<th width="11%">
							End Time
						</th>
						<th width="10%">
							Gold
						</th>
						<th width="22%">
							[hh/mm/ss] Game Duration
						</th>
						<th width="15%">
							Game's Secret
						</th>
					</tr>
				</thead>
				<tbody class="bg-warning bg-opacity-25">

					<tr>
						<td>
							<h5 style="color:saddlebrown">⋞<strong style="color:darkslateblue">@(count++)</strong>⋟</h5>
						</td>
						<td>
							<h6>@score.StartTime</h6>
						</td>
						<td>
							<h6>@score.EndTime</h6>
						</td>
						<td>
							<h6>@score.GoldForTheGame</h6>
						</td>

						<td>
							<h6>@(DateTime.Parse(score.EndTime) - DateTime.Parse(score.StartTime))</h6>
						</td>
						<td>
							<h6>@score.SecretNumber</h6>
						</td>
					</tr>
				</tbody>
			</table>

		}
	</div>
	<hr class="container w-75" />
	<hr class="container w-50" />
	<div>
		<div class="container align-content-center bg-success bg-opacity-25 w-25 rounded-pill">
			<h5>Total Gold Earned: ⭐<strong style="color:orangered">@Model.Sum(x=>x.GoldForTheGame).Value</strong>⭐</h5>
		</div>
	</div>
</div>