SecretNumberGame/Controllers/GameController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SecretNumberGame.Data.Constants;
using SecretNumberGame.Services.Contracts;
using SecretNumberGame.Services.Models;
using System.Collections.Immutable;
using System.Security.Claims;

namespace SecretNumberGame.Controllers
{
    public class GameController : BaseController
    {
        private readonly ISecretNumberService service;
        private readonly ISaveResultService saveResultService;

        public GameController(ISecretNumberService _service, ISaveResultService _saveResultService)
        {
            this.service = _service;
            saveResultService = _saveResultService;
        }
        [HttpGet]
        [Authorize(Roles =GlobalConstants.PLAYER)]
        public async Task<IActionResult> GetSecretNumber()
        {
            SecretNumberViewModel modelNumber = await service.GetSecretNumberAsync();

            return View(modelNumber);
        }
        [HttpPost]
        [Authorize(Roles = GlobalConstants.PLAYER)]
        public async Task<IActionResult> FindSecretNumber(string nums, int num, int col)
        {
            var modelNumber = await service.GetModelAsJson(nums,num,col);
            return Json(new { data = modelNumber });
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.PLAYER)]
        public async Task<IActionResult> CreateARecord(string secretNum, DateTime startDt, string bombs)
        {
            var userId = User?.Claims?.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)?.Value;
            if (userId == null)
            {
                return RedirectToAction("Index", "Home");
            }
            var model =  await saveResultService.CollectModelProperties(secretNum, startDt, bombs, userId);
            if (model == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("MyScore", "ScoreBoard");
        }

    }
}

SecretNumberGame/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bulls & Cows</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SecretNumberGame.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid bg-success bg-opacity-50">
                <a class="navbar-brand text-dark" asp-area="" asp-controller="Home" asp-action="Index"><strong>⊰Bulls & Cows⊱</strong></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 rounded-pill" style="background-color:greenyellow">
                        <li class="nav-item btn-group btn-outline-success rounded-pill">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>                        
                        @if (User?.Identity?.IsAuthenticated?? false)
                        {
                            <li class="nav-item btn-group btn-outline-success rounded-pill">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="GetSecretNumber">Start Game</a>
                            </li>
                            <li class="nav-item btn-group btn-outline-success rounded-pill">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ScoreBoard" asp-action="MyScore">My Score</a>
                            </li>
                        }
                          <li class="nav-item btn-group btn-outline-success rounded-pill">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ScoreBoard" asp-action="GetAllUsersScore">Global Score Results</a>
                          </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary bg-opacity-25">
        <div class="container">
            &copy; @DateTime.Now.Year - Bulls & Cows
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>    
    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("Notyf")
</body>
</html>

SecretNumberGame/Views/Shared/_gameIntro.cshtml
<div class="container collapse collapsing" id="collapseID">
    <div class="card card-body bg-warning bg-opacity-10 rounded-circle">
        <h3><strong>Main rules:</strong></h3>
        <h5>
            ⥽ A random number is generated each time you start a New game.
        </h5>
        <h5>
            Then you have the opportunity to choose position row and a number.
        </h5>
        <h5>
            If the number is present somewhere, the Cow will appear.
        </h5>
        <h5>
            If the number is missing - Bomb will explode.
        </h5>
        <h5>
            If the number is correctly guessed - the Bull will come out and a number will be revealed below.
        </h5>
        <h5>
            Collect all 7 numbers and submit to get your Score points.
        </h5>
        <h5>
            Be faster and you will earn even more points, slow timings will reduce points earned.
        </h5>
        <h5>
            Bombs occurances will lead to further overall points decrease. ⥼
        </h5>

    </div>
</div>